# Generated by Django 5.0.2 on 2024-08-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_livro_isbn_alter_livro_preco_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AddField(
            model_name="livro",
            name="coautor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros_coautor",
                to="core.autor",
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros_autor",
                to="core.autor",
            ),
        ),
    ]
